version: "3"
services:
  frontend:
    build: ./Frontend
    volumes:
      - ./frontend/src:/app/src:rw
    ports:
      - 4200:4200

  backend:
    build: ./Backend
    volumes:
      - ./backend/src:/app/src:rw
    ports:
      - 3000:3000